#!/bin/bash

set -e

git sync-tasks

changes=`git status --porcelain | wc -l`
if [ $changes -gt 0 ]; then
	echo "Stash or commit your changes first"
	exit 1
fi

echo Sync"'"ing master and testing

remote=$(git config "branch.master.remote")
git checkout master
git merge --no-ff --no-edit -m "Merge testing into master" testing
git checkout testing
git merge --ff-only master

git push $remote master testing
git checkout master
