#!/bin/bash

set -e

if [ "" == "$1" ]; then
	echo "Specify a task name to test"
	exit 1
fi

if [ "" == "$2" ]; then
	echo "Specify an environment (number) to test on"
	exit 1
fi

git task-sync

remote=$(git config "branch.master.remote")
task=$1
if [[ $task == task-* ]]; then
	task=${task:5}
fi

stat=`git task-status $task`
behindmaster=`git rev-list "$remote/task-$task..$remote/master" --no-merges | wc -l`

if [ "$stat" != "busy" ]; then
	echo "Task $task is not busy: $stat"
	exit 1
fi

if [ "$behindmaster" -gt "0" ]; then
	echo "Task $task is $behindmaster commit behind master, run git task-update $task first"
	exit 1
fi

git push --force $remote task-$task:env-$2
