#!/bin/bash

set -e

remote=$(git config "branch.master.remote")
curbranch=$(git rev-parse --abbrev-ref HEAD)

git fetch --prune

git checkout master
git merge $remote/master

git checkout testing
git merge $remote/testing

for i in `git task-list --local`; do
	git fast-forward task-$i
done

git push --all $remote

git checkout $curbranch
