#!/bin/bash

set -e
source "${0%[\\/]*}"/_git-common.sh

if [ "" == "$1" ]; then
	echo "Specify a task name to test"
	exit 1
fi

if [ "" == "$2" ]; then
	echo "Specify an environment (number) to test on"
	exit 1
fi

git task-sync

remote=$(git config "branch.v2.38.remote")
task=$1
if [[ $task == task-* ]]; then
	task=${task:5}
fi

stat=`git task-status $task`
behindmaster=`git rev-list "$remote/task-$task..$remote/v2.38" --no-merges | wc -l`

if [ "$stat" != "busy" ]; then
	echo "Task $task is not busy: $stat"
	exit 1
fi

if [ "$behindmaster" -gt "0" ]; then
	echo "Task $task is $behindmaster commit behind v2.38, run git task-update $task first"
	exit 1
fi

git push --force $remote task-$task:env-$2
