#!/bin/bash

set -e

remote=$(git config "branch.master.remote")
if [ "--local" == "$1" ]; then
	tasks=`git branch --list task\* | cut -f2- -d-`
else
	tasks=`git branch -r --list $remote/task\* | cut -f2- -d/ | cut -f2- -d-`
fi

for task in $tasks; do
	if [ "--simple" == "$2" ]; then
		echo $task
	else
		aheadtesting=`git rev-list "testing..$remote/task-$task" | wc -l`
		aheadmaster=`git rev-list "master..$remote/task-$task" | wc -l`
		if [ "$aheadtesting" -eq "0" ]; then
			if [ "$aheadmaster" -eq "0" ]; then
				status="not-started"
			else
				status="testing"
			fi
		else
			if [ "$aheadmaster" -eq "0" ]; then
				status="cheated"
			else
				if [ "$aheadmaster" -eq "$aheadtesting" ]; then
					status="busy"
				else
					status="rejected"
				fi
			fi
		fi
		echo "$task  [$status] ($aheadtesting not in testing; $aheadmaster not in master)"
	fi
done
