#!/bin/bash

remote=$(git config "branch.master.remote")
curbranch=$(git rev-parse --abbrev-ref HEAD)

git fetch --prune

git checkout master
git merge $remote/master

git checkout testing
git merge $remote/testing

git push --all $remote
