#!/bin/bash

git sync-tasks

if [ "" == "$1" ]; then
	echo "Specify a task name to switch to"
	exit 1
fi

changes=`git status --porcelain | wc -l`
if [ $changes -gt 0 ]; then
	echo "Stash or commit your changes first"
	exit 1
fi

task=$1
if [[ $task =~ ^task-.* ]]; then
	task=${task:5}
fi

git checkout task-$task
