#!/bin/bash

set -e
source "${0%[\\/]*}"/_git-common.sh

changes=`git status --porcelain | wc -l`
if [ $changes -gt 0 ]; then
	echo "Stash or commit your changes first"
	exit 1
fi

remote=$(git config "branch.v2.38.remote")

git fetch --prune
git fast-forward v2.38
git fast-forward master

for i in `git task-list --local --simple`; do
	if ! git branch -r | grep -q $remote/task-$i
	then
		ahead=`git rev-list "$remote/v2.38..task-$i" | wc -l`
		if [ "$ahead" -eq "0" ]; then
			git branch -D task-$i
		else
			git branch -d task-$i
		fi
	else
		git config --unset branch.task-$i.rebase || true
		git fast-forward task-$i || true
	fi
done

git push --all $remote 
