#!/bin/bash

set -e
source "${0%[\\/]*}"/_git-common.sh

function branchMenu() {
	function printBranchMenu() {
		echo "Selecteer een source-branch:"
		echo "m) master (volgende release)"
		echo "v) valuepack (volgende valuepack)"
		echo "a) acceptatie (acceptatie patch)"
		echo "p) patch (productie patch)"
	}
	printBranchMenu
	while :
	do
	    echo
		echo "Selecteer een optie [m,v,a,p]?"
		read CHOICE
	    case "$CHOICE" in
	        "m")
	            srcBranch="master"
	            break
	            ;;
	        "v")
	            srcBranch="valuepack"
	            break
	            ;;
	        "a")
	            srcBranch="acceptatie"
	            break
	            ;;
	        "p")
	            srcBranch="patch"
	            break
	            ;;
	    esac
	    echo "Ongeldige optie!"
	done
}

if [ "$#" -ne 1 ]; then
    echo "Usage: git task-start [source-branch] [task-]name"
    exit 1
fi

git task-sync || ( echo "git-task-sync failed"; exit 1 )

if [ "$#" -eq 1 ]; then
	task=$1
	srcBranch=""
	branchMenu
else
	task=$2   
	srcBranch=$1 
fi

if [[ $task == task-* ]]; then
	task=${task:5}
fi




echo Starting "'"task-$task"'"

remote=$(git config "branch.master.remote")
git checkout -b task-$task $srcBranch
git push -u $remote task-$task
git config --unset branch.task-$task.rebase || true


