#!/bin/bash

set -e
source "${0%[\\/]*}"/_git-common.sh
main=$(git rev-parse --abbrev-ref origin/HEAD | cut -f2 -d/)

if [ "" == "$1" ]; then
	echo "Specify a task name to start"
	exit 1
fi

git task-sync || ( echo "git-task-sync failed"; exit 1 )

task=$1
if [[ $task == task-* ]]; then
	task=${task:5}
fi

echo Starting "'"task-$task"'"

remote=$(git config "branch.$main.remote")
git checkout -b task-$task $main
git push -u $remote task-$task
git config --unset branch.task-$task.rebase || true
