#!/bin/bash

set -e

git task-sync

echo Sync"'"ing master and testing

remote=$(git config "branch.master.remote")
git checkout master
git merge --no-ff --no-edit -m "Merge testing into master" testing
git checkout testing
git merge --ff-only master

git push $remote master testing
git checkout master
