#!/bin/bash

set -e
source "${0%[\\/]*}"/_git-common.sh

curbranch=$(git rev-parse --symbolic-full-name HEAD)
from=`git rev-parse --symbolic-full-name "$1"`
if [ "" != "$2" ]; then
	tobranch=$2
else
	remote=$(git config "branch.$1.remote"||true)
	if [ "$remote" == "" ]; then
		remote="origin"
	fi
	tobranch=$remote/$1
fi
to=`git rev-parse --symbolic-full-name "$tobranch"`

if [ -n "`git rev-list "$to..$from"`" ]
then
	echo "`git rev-parse --abbrev-ref $from` has local commits; can't fast-forward"
	exit 1
fi

if [ "$curbranch" != "$from" ]; then
	git update-ref -m ff-branch "$from" "$to"
else
	git merge --ff-only "$to"
fi
