#!/bin/bash

set -e

changes=`git status --porcelain | wc -l`
if [ $changes -gt 0 ]; then
	echo "Stash or commit your changes first"
	exit 1
fi

remote=$(git config "branch.master.remote")
curbranch=$(git rev-parse --abbrev-ref HEAD)

git fetch --prune

git checkout master
git merge $remote/master

git checkout testing
git merge $remote/testing

for i in `git task-list --local --simple`; do
	git fast-forward task-$i
done

git push --all $remote

git checkout $curbranch
