#!/bin/bash

git sync-tasks

if [ "" == "$1" ]; then
	echo "Specify a task name to start"
	exit 1
fi

changes=`git status --porcelain | wc -l`
if [ $changes -gt 0 ]; then
	echo "Stash or commit your changes first"
	exit 1
fi

task=$1
if [[ $task =~ ^task-.* ]]; then
	task=${task:5}
fi

echo Starting "'"task-$task"'"

remote=$(git config "branch.master.remote")
git checkout -b task-$task master
git push -u $remote task-$task
