#!/bin/bash

git sync-tasks

if [ "" == "$1" ]; then
	echo "Specify a task name to mark done or --continue to continue merging"
	exit 1
fi

changes=`git status --porcelain | wc -l`
if [ $changes -gt 0 ]; then
	echo "Stash or commit your changes first"
	exit 1
fi

taskfile="$(git rev-parse --git-dir)/TASK_NAME"
if [ "--continue" != "$1" ]; then
	task=$1
	if [[ $task =~ ^task-.* ]]; then
		task=${task:5}
	fi
	echo $task > $taskfile

	echo Marking "'"task-$task"'" done

	git checkout master
	git merge --no-ff --no-edit -m "Mark task-$task done" task-$task

	rc=$?
	if [[ $rc != 0 ]]; then
		echo " - Fix the merge conflicts"
		echo " - run 'git add -A' or 'git add <file>'"
		echo " - run 'git commit'"
		echo " - run 'git task-done --continue'"
		exit 1
	fi
else
	task=`cat $taskfile`
fi

rm $taskfile
remote=$(git config "branch.master.remote")
git push $remote master :task-$task
git branch -d task-$task
