#!/bin/bash

set -e
source "${0%[\\/]*}"/_git-common.sh

if [ "" == "$1" ]; then
	echo "Specify a task name to switch to"
	exit 1
fi

git task-sync

task=$1
if [[ $task == task-* ]]; then
	task=${task:5}
fi

git checkout task-$task
git config --unset branch.task-$task.rebase || true
