#!/bin/bash

set -e
source "${0%[\\/]*}"/_git-common.sh
main=$(git rev-parse --abbrev-ref origin/HEAD | cut -f2 -d/)

task=$1
if [ "" == "$1" ]; then
	task=$(git rev-parse --abbrev-ref HEAD)

	if [ $main == $task ]; then
		echo "Specify a task name to update"
		exit 1
	fi
fi

git task-sync

if [[ $task == task-* ]]; then
	task=${task:5}
fi

remote=$(git config "branch.$main.remote")
git checkout task-$task
git merge $remote/$main
