#!/bin/bash

set -e
source "${0%[\\/]*}"/_git-common.sh

if [ "" == "$1" ]; then
	echo "Specify a task name to update"
	exit 1
fi

git task-sync

task=$1
if [[ $task == task-* ]]; then
	task=${task:5}
fi

remote=$(git config "branch.v2.38.remote")
git checkout task-$task
git merge $remote/v2.38
