#!/bin/bash

set -e
source "${0%[\\/]*}"/_git-common.sh

if [ "$#" -ne 2 ]; then
    echo "Usage: git task-start source-branch [task-]name"
    exit 1
fi

git task-sync || ( echo "git-task-sync failed"; exit 1 )

task=$2
if [[ $task == task-* ]]; then
	task=${task:5}
fi

echo Starting "'"task-$task"'"

remote=$(git config "branch.master.remote")
git checkout -b task-$task $1
git push -u $remote task-$task
git config --unset branch.task-$task.rebase || true
