#!/bin/bash

set -e
source "${0%[\\/]*}"/_git-common.sh
main=$(git rev-parse --abbrev-ref origin/HEAD | cut -f2 -d/)

remote=$(git config "branch.$main.remote")
if [ "--local" == "$1" ]; then
	tasks=`git branch --list task\* | cut -f2- -d-`
else
	tasks=`git branch -r --list $remote/task\* | cut -f2- -d/ | cut -f2- -d-`
fi

for task in $tasks; do
	if [ "--simple" == "$2" ]; then
		echo $task
	else
		stat=`git task-status $task`
		aheadmain=`git rev-list "$remote/$main..$remote/task-$task" --no-merges | wc -l`
		behindmain=`git rev-list "$remote/task-$task..$remote/$main" --no-merges | wc -l`
		author=`git shortlog -s -n --no-merges "$remote/$main..$remote/task-$task" | cut -f 2- | head -n 1`
		printf '%-20s [%-16s] %4d behind/%4d ahead of %s   %s\n' "$task" "$stat" "$behindmain" "$aheadmain" "$main" "$author"
	fi
done
