#!/bin/bash

set -e
source "${0%[\\/]*}"/_git-common.sh

if [ "" == "$1" ]; then
	echo "No task specified"
	exit 1
fi

remote=$(git config "branch.master.remote")
task=$1
if [[ $task == task-* ]]; then
	task=${task:5}
fi

aheadmaster=`git rev-list "$remote/master..$remote/task-$task" --no-merges | wc -l`
if [ "$aheadmaster" -eq "0" ]; then
	echo "not-started"
else
	envs=`git branch -r --list $remote/env-\* | cut -f2- -d/ | cut -f2- -d-`
	for env in $envs; do
		envhash=`git rev-parse $remote/env-$env`
		taskhash=`git rev-parse $remote/task-$task`
		if [[ "$envhash" == "$taskhash" ]]; then
			echo "testing on env-$env"
			exit 0
		fi
	done

	for env in $envs; do
		aheadenv=`git rev-list "$remote/env-$env..$remote/task-$task" --no-merges | wc -l`
		if [ "$aheadenv" -eq "0" ]; then
			echo "merged in env-$env"
			exit 0
		fi
	done
	echo "busy"
fi
